//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Benday.SqlUtils.WpfUi {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.6.0.0")]
    internal sealed partial class SqlUtilSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static SqlUtilSettings defaultInstance = ((SqlUtilSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SqlUtilSettings())));
        
        public static SqlUtilSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AppInsightsUserId {
            get {
                return ((string)(this["AppInsightsUserId"]));
            }
            set {
                this["AppInsightsUserId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AppInsightsUserSessionIsFirst {
            get {
                return ((string)(this["AppInsightsUserSessionIsFirst"]));
            }
            set {
                this["AppInsightsUserSessionIsFirst"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AppInsightsTelemetryEnabled {
            get {
                return ((string)(this["AppInsightsTelemetryEnabled"]));
            }
            set {
                this["AppInsightsTelemetryEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsFirstRunOfApp {
            get {
                return ((bool)(this["IsFirstRunOfApp"]));
            }
            set {
                this["IsFirstRunOfApp"] = value;
            }
        }
    }
}
